### PR TITLE
Fix a typo: registed -> registerred

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Comment by alick** [comment]
嘿，register 不双写吧 @felixonmars @bigeagle

**Comment by felixonmars** [comment]
我看似乎两种写法都有，于是按上下文保持了一致。

**Comment by alick** [comment]
英语语法/词法上应该不双写。

On Mon, Mar 21, 2016 at 1:28 PM, Felix Yan notifications@github.com wrote:

> 我看似乎两种写法都有，于是按上下文保持了一致。
> 
> On Tue, Mar 22, 2016, 01:26 Alick Zhao notifications@github.com wrote:
> 
> > 嘿，register 不双写吧 @felixonmars https://github.com/felixonmars @bigeagle
> > https://github.com/bigeagle
> > 
> > —
> > You are receiving this because you were mentioned.
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/tuna/fishroom/pull/17#issuecomment-199388620
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/tuna/fishroom/pull/17#issuecomment-199414760

## 

Regards,
Alick

**Comment by xiaq** [comment]
双写也要按照基本法，按照英语拼写的法来产生啊。

register 词尾 r 不双写：https://en.wiktionary.org/wiki/register#Verb

**Pull request merged**
